// 170 Kelimelik Veri Seti (Alfabetik Sıralanmış)
    const dictionary = [
        { w: "Ahlak", d: "İnsanların uyması gereken kurallar bütünü.", c: "Felsefe" },
        { w: "Akapunktur", d: "Vücudun belirli noktalarına iğne batırılarak yapılan tedavi.", c: "Sağlık" },
        { w: "Akreditif", d: "Ticarette bir bankanın ödeme garantisi vermesi.", c: "Ticaret" },
        { w: "Aktif Taşıma", d: "Hücrelerin enerji harcayarak madde taşıması.", c: "Biyoloji" },
        { w: "Algı", d: "Duyularla alınan bilgilerin yorumlanması.", c: "Psikoloji" },
        { w: "Anatomi", d: "Canlıların vücut yapısını inceleyen dal.", c: "Biyoloji" },
        { w: "Anayasa", d: "Bir devletin temel kanunlar bütünü.", c: "Sosyoloji" },
        { w: "Antik", d: "Eski çağlardan kalma eser veya yapı.", c: "Tarih" },
        { w: "Arz", d: "Piyasaya sunulan mal veya hizmet miktarı.", c: "Ekonomi" },
        { w: "Astrofizik", d: "Gök cisimlerinin fiziksel özelliklerini inceleyen bilim.", c: "Evren" },
        { w: "Atalet", d: "Bir cismin hareket durumunu koruma isteği.", c: "Fizik" },
        { w: "Atom", d: "Maddenin en küçük yapı taşı.", c: "Fizik" },
        { w: "Ayet", d: "Kutsal kitapların her bir cümlesi.", c: "İnanç" },
        { w: "Bağışıklık", d: "Vücudun hastalıklara karşı savunma gücü.", c: "Sağlık" },
        { w: "Bakiye", d: "Hesapta kalan miktar.", c: "Ekonomi" },
        { w: "Barok", d: "Abartılı ve süslü bir sanat üslubu.", c: "Sanat" },
        { w: "Bilişsel", d: "Zihinsel süreçlerle ilgili olan.", c: "Eğitim" },
        { w: "Biyoetik", d: "Biyolojik bilimlerdeki ahlaki tartışmalar.", c: "Biyoloji" },
        { w: "Biyosfer", d: "Dünya üzerinde canlıların yaşadığı tabaka.", c: "Coğrafya" },
        { w: "Borsa", d: "Hisse senetlerinin alınıp satıldığı yer.", c: "Ekonomi" },
        { w: "Bulutsu", d: "Uzaydaki gaz ve toz yığınları.", c: "Evren" },
        { w: "Burs", d: "Eğitim için verilen maddi destek.", c: "Eğitim" },
        { w: "Ciro", d: "Bir işletmenin toplam satışı.", c: "Ticaret" },
        { w: "Coğrafya", d: "Yeryüzü şekillerini inceleyen bilim.", c: "Coğrafya" },
        { w: "Cumhuriyet", d: "Halkın kendi kendini yönettiği rejim.", c: "Tarih" },
        { w: "Cüce Gezegen", d: "Küçük yapılı gezegen türü.", c: "Evren" },
        { w: "Çekim Yasası", d: "Kütlelerin birbirini çekmesi prensibi.", c: "Fizik" },
        { w: "Çelişki", d: "İki düşüncenin birbirine uymaması.", c: "Felsefe" },
        { w: "Debi", d: "Akarsuyun saniyede akıttığı su miktarı.", c: "Coğrafya" },
        { w: "Deflasyon", d: "Fiyatların genel seviyesinin düşmesi.", c: "Ekonomi" },
        { w: "Demokrasi", d: "Eşitlikçi yönetim biçimi.", c: "Sosyoloji" },
        { w: "Deney", d: "Bilimsel bir varsayımı test etme süreci.", c: "Eğitim" },
        { w: "Dermotoloji", d: "Deri hastalıkları bilimi.", c: "Sağlık" },
        { w: "Devrim", d: "Toplumsal yapının köklü değişimi.", c: "Tarih" },
        { w: "Dış Ticaret", d: "Ülkeler arası mal alışverişi.", c: "Ticaret" },
        { w: "Dinamik", d: "Hareketli ve değişken süreçler.", c: "Fizik" },
        { w: "Diplomasi", d: "Uluslararası ilişkiler sanatı.", c: "Sosyoloji" },
        { w: "Diyabet", d: "Şeker hastalığı.", c: "Sağlık" },
        { w: "Dogma", d: "Sorgulanmadan kabul edilen inanç.", c: "İnanç" },
        { w: "Duygu", d: "İçsel hislerin yansıması.", c: "Duygular" },
        { w: "Edebiyat", d: "Düşüncelerin sanatsal dille anlatımı.", c: "Sanat" },
        { w: "Ego", d: "Kişinin benlik bilinci.", c: "Psikoloji" },
        { w: "Ekoloji", d: "Doğa ve canlı ilişkisini inceleyen bilim.", c: "Biyoloji" },
        { w: "Ekosistem", d: "Canlı ve cansız çevrenin bütünü.", c: "Coğrafya" },
        { w: "Elektron", d: "Atomdaki negatif yüklü parçacık.", c: "Fizik" },
        { w: "Empati", d: "Kendini başkasının yerine koyma.", c: "Duygular" },
        { w: "Endokrin", d: "Hormon sistemini inceleyen dal.", c: "Sağlık" },
        { w: "Enerji", d: "İş yapabilme kapasitesi.", c: "Fizik" },
        { w: "Enflasyon", d: "Fiyatların sürekli artması.", c: "Ekonomi" },
        { w: "Envanter", d: "Eldeki mal listesi.", c: "Ticaret" },
        { w: "Epistemoloji", d: "Bilgi felsefesi.", c: "Felsefe" },
        { w: "Erozyon", d: "Toprağın aşınarak taşınması.", c: "Coğrafya" },
        { w: "Estetik", d: "Güzellik algısı ve felsefesi.", c: "Sanat" },
        { w: "Etik", d: "Ahlaki değerler bütünü.", c: "Felsefe" },
        { w: "Evren", d: "Gök cisimlerini içine alan sonsuz boşluk.", c: "Evren" },
        { w: "Faiz", d: "Paranın kullanım bedeli.", c: "Ekonomi" },
        { w: "Fanatizm", d: "Bir düşünceye körü körüne bağlılık.", c: "Spor" },
        { w: "Fantezi", d: "Sınırsız hayal gücü.", c: "Psikoloji" },
        { w: "Ferman", d: "Padişahın yazılı emri.", c: "Tarih" },
        { w: "Fosil", d: "Taşlaşmış canlı kalıntısı.", c: "Tarih" },
        { w: "Fotoğraf", d: "Işıkla görüntüleme sanatı.", c: "Sanat" },
        { w: "Fotosentez", d: "Bitkilerin ışıkla besin üretmesi.", c: "Biyoloji" },
        { w: "Galaksi", d: "Yıldız kümeleri sistemi.", c: "Evren" },
        { w: "Gayri Safi Milli Hasıla", d: "Ülkenin toplam ekonomik üretimi.", c: "Ekonomi" },
        { w: "Gen", d: "Kalıtımsal bilgi birimi.", c: "Biyoloji" },
        { w: "Girişimci", d: "Risk alarak iş kuran kişi.", c: "Ticaret" },
        { w: "Güdü", d: "Eyleme geçiren içsel güç.", c: "Psikoloji" },
        { w: "Hadis", d: "Peygamberin söz ve davranışları.", c: "İnanç" },
        { w: "Hafıza", d: "Bilgiyi saklama yetisi.", c: "Psikoloji" },
        { w: "Halkoylaması", d: "Önemli kararlar için halkın oyuna başvurma.", c: "Sosyoloji" },
        { w: "Hasret", d: "Bir şeye duyulan özlem.", c: "Duygular" },
        { w: "Hata", d: "İstenmeden yapılan yanlış.", c: "Eğitim" },
        { w: "Hicret", d: "Bir yerden başka yere göç etme.", c: "İnanç" },
        { w: "Hijyen", d: "Sağlığı koruma temizliği.", c: "Sağlık" },
        { w: "Hiyeroglif", d: "Eski Mısır resim yazısı.", c: "Tarih" },
        { w: "Hukuk", d: "Toplum düzenini sağlayan yasalar.", c: "Sosyoloji" },
        { w: "Huzur", d: "İçsel dinginlik hali.", c: "Duygular" },
        { w: "Hücre", d: "Canlılığın en küçük birimi.", c: "Biyoloji" },
        { w: "Isı", d: "Maddeler arası aktarılan enerji.", c: "Fizik" },
        { w: "Işık Yılı", d: "Işığın bir yılda aldığı yol.", c: "Evren" },
        { w: "İbadet", d: "Dini görevleri yerine getirme.", c: "İnanç" },
        { w: "İhracat", d: "Yurt dışına mal satma.", c: "Ticaret" },
        { w: "İktisat", d: "Kaynakların verimli kullanımı bilimi.", c: "Ekonomi" },
        { w: "İllüzyon", d: "Göz yanılması.", c: "Sanat" },
        { w: "İmge", d: "Zihinde canlandırılan görüntü.", c: "Sanat" },
        { w: "İnovasyon", d: "Yenilikçi buluş ve uygulamalar.", c: "Ticaret" },
        { w: "İrade", d: "Karar verme ve uygulama gücü.", c: "Felsefe" },
        { w: "İstihdam", d: "İş gücünün işe yerleştirilmesi.", c: "Ekonomi" },
        { w: "İthalat", d: "Yurt dışından mal alma.", c: "Ticaret" },
        { w: "Jeopolitik", d: "Coğrafyanın siyasete etkisi.", c: "Coğrafya" },
        { w: "Kader", d: "İlahi belirleme ve plan.", c: "İnanç" },
        { w: "Kalıtım", d: "Özelliklerin nesilden nesile geçmesi.", c: "Biyoloji" },
        { w: "Kandil", d: "Özel dini geceler.", c: "İnanç" },
        { w: "Kara Delik", d: "Çekimi çok güçlü uzay bölgesi.", c: "Evren" },
        { w: "Kardiyoloji", d: "Kalp ve damar hastalıkları dalı.", c: "Sağlık" },
        { w: "Karizma", d: "Etkileyici kişilik özelliği.", c: "Psikoloji" },
        { w: "Kuvvet", d: "Cisimlerin hareketini değiştiren etki.", c: "Fizik" },
        { w: "Kültür", d: "Toplumun yaşam tarzı ve değerleri.", c: "Sosyoloji" },
        { w: "Lider", d: "Grubu yöneten ve yönlendiren kişi.", c: "Sosyoloji" },
        { w: "Lirik", d: "Coşkulu ve duygusal anlatım.", c: "Sanat" },
        { w: "Lojistik", d: "Ürünlerin taşınma ve depolanma süreci.", c: "Ticaret" },
        { w: "Maliyet", d: "Bir ürünün üretim gideri.", c: "Ekonomi" },
        { w: "Mantık", d: "Doğru düşünme kuralı.", c: "Felsefe" },
        { w: "Maneviyat", d: "Ruhsal ve içsel değerler.", c: "İnanç" },
        { w: "Melankoli", d: "Derin hüzün ve keder hali.", c: "Duygular" },
        { w: "Merak", d: "Öğrenme isteği.", c: "Eğitim" },
        { w: "Metafor", d: "Mecazi anlatım türü.", c: "Eğitim" },
        { w: "Metafizik", d: "Fizik ötesi konuları inceleyen felsefe.", c: "Felsefe" },
        { w: "Meteor", d: "Atmosfere giren gök taşı.", c: "Evren" },
        { w: "Metabolizma", d: "Vücuttaki kimyasal süreçler.", c: "Sağlık" },
        { w: "Mitoloji", d: "Efsaneler bütünü.", c: "Tarih" },
        { w: "Mutluluk", d: "Genel iyilik ve sevinç hali.", c: "Duygular" },
        { w: "Müfredat", d: "Eğitim programının içeriği.", c: "Eğitim" },
        { w: "Müzik", d: "Seslerin sanatsal düzeni.", c: "Sanat" },
        { w: "Nebula", d: "Yıldızlararası toz bulutu.", c: "Evren" },
        { w: "Nefret", d: "Aşırı sevgisizlik ve düşmanlık.", c: "Duygular" },
        { w: "Nezaket", d: "Zarif ve saygılı davranış.", c: "Duygular" },
        { w: "Nöron", d: "Sinir hücresi.", c: "Sağlık" },
        { w: "Nüfus", d: "Bir yerdeki toplam insan sayısı.", c: "Coğrafya" },
        { w: "Olimpiyat", d: "Dünya çapında spor müsabakaları.", c: "Spor" },
        { w: "Onur", d: "Öz saygı ve şeref.", c: "Duygular" },
        { w: "Optik", d: "Işık olaylarını inceleyen dal.", c: "Fizik" },
        { w: "Otomasyon", d: "İşlerin makinelerle yapılması.", c: "Ticaret" },
        { w: "Öğrenme", d: "Bilgi edinme süreci.", c: "Eğitim" },
        { w: "Önyargı", d: "Peşin hüküm verme.", c: "Psikoloji" },
        { w: "Özveri", d: "Kendinden ödün verme.", c: "Duygular" },
        { w: "Paleontoloji", d: "Fosil bilim dalı.", c: "Tarih" },
        { w: "Pandomim", d: "Sessiz hareketli sanat.", c: "Sanat" },
        { w: "Pazar", d: "Ticaretin yapıldığı ortam.", c: "Ticaret" },
        { w: "Pedagoji", d: "Çocuk eğitimi bilimi.", c: "Eğitim" },
        { w: "Performans", d: "Bir işin sergilenme başarısı.", c: "Spor" },
        { w: "Plato", d: "Yüksekte kalan düzlük.", c: "Coğrafya" },
        { w: "Politika", d: "Devlet yönetme sanatı.", c: "Sosyoloji" },
        { w: "Psikanaliz", d: "Bilinçaltı inceleme yöntemi.", c: "Psikoloji" },
        { w: "Rant", d: "Emeksiz elde edilen gelir.", c: "Ekonomi" },
        { w: "Rasyonalizm", d: "Akılcılık akımı.", c: "Felsefe" },
        { w: "Rehabilitasyon", d: "Yeniden uyum sağlama tedavisi.", c: "Sağlık" },
        { w: "Resesyon", d: "Ekonomik duraklama.", c: "Ekonomi" },
        { w: "Ruh", d: "Manevi varlık unsuru.", c: "İnanç" },
        { w: "Sabır", d: "Zorluklara dayanma gücü.", c: "Duygular" },
        { w: "Sağlık", d: "Bedensel ve ruhsal iyilik hali.", c: "Sağlık" },
        { w: "Sanat", d: "Güzelliğin ifadesi olan yaratıcılık.", c: "Sanat" },
        { w: "Sembol", d: "Bir kavramın simgesi.", c: "Sanat" },
        { w: "Sermaye", d: "Yatırım için gereken varlık.", c: "Ekonomi" },
        { w: "Sevgi", d: "Derin bağlılık hissi.", c: "Duygular" },
        { w: "Siyaset", d: "Ülke yönetimi işleri.", c: "Sosyoloji" },
        { w: "Sosyoloji", d: "Toplum bilimi.", c: "Sosyoloji" },
        { w: "Spekülasyon", d: "Fiyat değişiminden kar elde etme.", c: "Ticaret" },
        { w: "Spor", d: "Fiziksel ve zihinsel antrenman.", c: "Spor" },
        { w: "Strateji", d: "Hedefe ulaşma planı.", c: "Spor" },
        { w: "Stres", d: "Zihinsel baskı ve gerginlik.", c: "Psikoloji" },
        { w: "Süpernova", d: "Yıldız patlaması.", c: "Evren" },
        { w: "Şefkat", d: "Acıyarak ve koruyarak sevme.", c: "Duygular" },
        { w: "Tarih", d: "Geçmiş olayları inceleyen bilim.", c: "Tarih" },
        { w: "Tasarruf", d: "Kaynakları dikkatli kullanma.", c: "Ekonomi" },
        { w: "Teoloji", d: "Tanrı bilimi.", c: "İnanç" },
        { w: "Teori", d: "Sistemli açıklama modeli.", c: "Eğitim" },
        { w: "Terapi", d: "İyileştirme yöntemi.", c: "Psikoloji" },
        { w: "Ticaret", d: "Kazanç amacıyla yapılan alım satım.", c: "Ticaret" },
        { w: "Tiyatro", d: "Sahnede canlandırma sanatı.", c: "Sanat" },
        { w: "Toplum", d: "Birlikte yaşayan insan topluluğu.", c: "Sosyoloji" },
        { w: "Üretim", d: "Mal ve hizmet ortaya koyma.", c: "Ticaret" },
        { w: "Ütopya", d: "Hayali ideal toplum düzeni.", c: "Felsefe" },
        { w: "Varlık", d: "Var olan her şey.", c: "Felsefe" },
        { w: "Vatandaş", d: "Aynı yurtta yaşayan birey.", c: "Sosyoloji" },
        { w: "Vektör", d: "Yönü ve şiddeti olan büyüklük.", c: "Fizik" },
        { w: "Vergi", d: "Kamu hizmeti için halktan alınan para.", c: "Ekonomi" },
        { w: "Vicdan", d: "İçsel ahlak mahkemesi.", c: "Duygular" },
        { w: "Virüs", d: "Hastalık yapıcı çok küçük varlık.", c: "Sağlık" },
        { w: "Yağış", d: "Havadaki nemin yere düşmesi.", c: "Coğrafya" },
        { w: "Yatırım", d: "Gelecek için kaynak ayırma.", c: "Ticaret" },
        { w: "Yerçekimi", d: "Dünya'nın merkezine doğru çekim.", c: "Fizik" },
        { w: "Yörünge", d: "Gök cisminin izlediği yol.", c: "Evren" },
        { w: "Zeka", d: "Problem çözme ve anlama yetisi.", c: "Psikoloji" },
        { w: "Ziyaret", d: "Birini görmeye gitme.", c: "İnanç" }
    ];
	